export interface ServiceAreaData {
  service: string;
  serviceSlug: string;
  area: string;
  areaSlug: string;
  description: string;
  benefits: string[];
  image: string;
  plz?: string;
}

export const SERVICE_AREAS: ServiceAreaData[] = [
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Hamm',
    areaSlug: 'hamm',
    description: 'Professionelle Damenhaarschnitte, Balayage und Colorationen direkt in Hamburg-Hamm mit über 20 Jahren Erfahrung.',
    benefits: [
      'Meisterqualität seit 2004 direkt vor Ort',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Hochwertige Produkte für langanhaltende Ergebnisse',
      'Mehrsprachige Beratung (Deutsch, Englisch, Türkisch, Persisch)',
      'Afterwork-Termine nach 19:00 Uhr möglich',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Borgfelde',
    areaSlug: 'borgfelde',
    description: 'Nur 5-10 Minuten von Borgfelde entfernt: Professionelle Damenhaarschnitte mit Meisterqualität seit 2004.',
    benefits: [
      'Kurze Anfahrt aus Borgfelde – ca. 5-10 Minuten',
      'U2/U4 zu Burgstraße oder Buslinien 25, 130',
      'Spezialisiert auf Damenschnitte und Colorationen',
      '245+ Google-Bewertungen mit 4.9 Sternen',
      'Entspannte Atmosphäre und individuelle Beratung',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Horn',
    areaSlug: 'horn',
    description: 'Damenfriseur für Horn-Kunden: Professionelle Haarschnitte und Colorationen mit kurzer Anfahrtszeit.',
    benefits: [
      'Etwa 10 Minuten von Horn entfernt',
      'U2 zu Burgstraße oder mit dem Fahrrad erreichbar',
      'Spezialisiert auf anspruchsvolle Haarschnitte',
      'Freundliches Team mit langem Erfahrungsrucksack',
      'Afterwork-Termine für berufstätige Frauen',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Eilbek',
    areaSlug: 'eilbek',
    description: 'Damenfriseur in Eilbek-Nähe: Meisterbetrieb mit Spezialisierung auf Balayage und moderne Färbetechniken.',
    benefits: [
      'Ca. 10 Minuten von Eilbek entfernt',
      'U1 oder U3 zur nächsten Haltestelle, dann leicht zu erreichen',
      'Spezialisiert auf Balayage und moderne Techniken',
      'Mehrsprachiges Team (Deutsch, Englisch, Türkisch, Persisch)',
      'Individuelle Konsultation für jeden Haartyp',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Wandsbek',
    areaSlug: 'wandsbek',
    description: 'Damenfriseur für Wandsbek-Bewohner: Professionelle Haarschnitte mit hervorragender U-Bahn-Anbindung.',
    benefits: [
      'Gute Verbindung von Wandsbek via U1 und Buslinien 25, 130',
      'Ca. 10-15 Minuten Fahrzeit',
      'Höchste Qualitätsstandards seit 2004',
      'Breites Leistungsspektrum: Schnitte, Colorationen, Balayage',
      'Flexible Afterwork-Termine für Berufstätige',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Billstedt',
    areaSlug: 'billstedt',
    description: 'Damenfriseur für Billstedt: Hervorragende U-Bahn-Verbindung mit professioneller Meisterqualität.',
    benefits: [
      'Direkte U2-Verbindung von Billstedt (ca. 15-20 Minuten)',
      'Einfache Anfahrt für Pendler',
      '245+ Google-Bewertungen mit 4.9 Sternen',
      'Spezialisiert auf Colorationen und Balayage',
      'Faire Preise und transparente Preisliste',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Mitte',
    areaSlug: 'mitte',
    description: 'Damenfriseur für Hamburg-Mitte: Zentral erreichbar mit Meisterbetrieb-Qualität.',
    benefits: [
      'Ca. 10-15 Minuten von Hamburg-Mitte entfernt',
      'U2 oder U4 zu Burgstraße oder S-Bahn zum Hauptbahnhof',
      'Entspannte Atmosphäre weg vom Trubel der Innenstadt',
      'Faire Preise: Damenschnitt ab 43€',
      'Mehrsprachige Konsultation für internationale Gäste',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20099',
  },
  {
    service: 'Damenfriseur',
    serviceSlug: 'damenfriseur',
    area: 'Bergedorf',
    areaSlug: 'bergedorf',
    description: 'Damenfriseur für Bergedorf-Kunden: Premium-Service mit S-Bahn und U-Bahn-Anbindung.',
    benefits: [
      'S21 zum Hauptbahnhof, dann U2/U4 zu Burgstraße (ca. 25-30 Min)',
      'Alternativ mit Auto via B5 in etwa 25 Minuten',
      'Eines der höchstbewerteten Salons in Hamburg: 4.9 Sterne',
      'Spezialisiert auf Balayage und Premium-Haarschnitte',
      'Beratung in mehreren Sprachen für internationale Kunden',
    ],
    image: 'https://images.pexels.com/photos/3993467/pexels-photo-3993467.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '21029',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Hamm',
    areaSlug: 'hamm',
    description: 'Herrenfriseur in Hamburg-Hamm: Moderne Haarschnitte, Bartpflege und Gentleman-Service vom Meister.',
    benefits: [
      'Inhaber Serbay Eskici ist Herrenspezialist mit 20+ Jahren Erfahrung',
      'Moderne Schnitt- und Styling-Techniken',
      'Professionelle Bartpflege und -beratung',
      'Entspannte Atmosphäre für den Mann von heute',
      'Afterwork-Termine nach 19:00 Uhr möglich',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Borgfelde',
    areaSlug: 'borgfelde',
    description: 'Herrenfriseur für Borgfelde: Nur 5-10 Minuten entfernt mit Meisterqualität für Moderne Herrenschnitte.',
    benefits: [
      'Kurze Anfahrt aus Borgfelde – ca. 5-10 Minuten mit U-Bahn',
      'Spezialisiert auf Herrenschnitte und Bartpflege',
      '245+ zufriedene Kunden mit 4.9 Sternen',
      'Freundliches Team, keine Wartezeiten',
      'Gentleman-Paket inkl. Schnitt, Bart & Augenbrauen ab 49€',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Horn',
    areaSlug: 'horn',
    description: 'Herrenfriseur für Horn-Bewohner: Professionelle Herrenschnitte mit kurzer Anfahrtszeit.',
    benefits: [
      'Etwa 10 Minuten von Horn erreichbar',
      'U2 zu Burgstraße oder mit Fahrrad',
      'Meisterqualität mit hohen Standards',
      'Spezialisiert auf anspruchsvolle Herrenschnitte',
      'Bartberatung und -styling für gehobene Ansprüche',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Eilbek',
    areaSlug: 'eilbek',
    description: 'Herrenfriseur in Eilbek-Nähe: Moderne Schnitte und Bartpflege von Meistern.',
    benefits: [
      'Ca. 10 Minuten von Eilbek entfernt',
      'Leicht mit U-Bahn oder Auto zu erreichen',
      'Meisterbetrieb seit 2004 mit hohem Qualitätsstandard',
      'Spezialisiert auf Herrenschnitte und Bartmodellage',
      'Individuelle Konsultation und angepasster Service',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Wandsbek',
    areaSlug: 'wandsbek',
    description: 'Herrenfriseur für Wandsbek: Professionelle Haarschnitte mit guter U-Bahn-Anbindung.',
    benefits: [
      'Gute Verbindung von Wandsbek via U1 und Busse',
      'Ca. 10-15 Minuten Fahrtzeit',
      'Meisterqualität und breites Leistungsspektrum',
      'Spezialisiert auf Herrenschnitte und Bartpflege',
      'Afterwork-Termine für arbeitstätige Männer',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Billstedt',
    areaSlug: 'billstedt',
    description: 'Herrenfriseur für Billstedt: Meisterqualität mit direkter U2-Verbindung.',
    benefits: [
      'Direkte U2-Verbindung von Billstedt (ca. 15-20 Minuten)',
      'Einfache Erreichbarkeit für Pendler',
      '245+ Google-Bewertungen mit 4.9 Sternen',
      'Spezialisiert auf moderne Herrenschnitte',
      'Faire Preise: Schnitt ab 18€',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Mitte',
    areaSlug: 'mitte',
    description: 'Herrenfriseur für Hamburg-Mitte: Moderne Schnitte zentral und leicht erreichbar.',
    benefits: [
      'Ca. 10-15 Minuten von Hamburg-Mitte entfernt',
      'U2/U4 zu Burgstraße, direkt vom Hauptbahnhof erreichbar',
      'Meisterqualität mit entspannter Atmosphäre',
      'Moderne Schnitt- und Styling-Techniken',
      'Faire Preise: Design-Schnitt ab 34€',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20099',
  },
  {
    service: 'Herrenfriseur',
    serviceSlug: 'herrenfriseur',
    area: 'Bergedorf',
    areaSlug: 'bergedorf',
    description: 'Herrenfriseur für Bergedorf: Premium-Service mit S-Bahn und U-Bahn-Verbindung.',
    benefits: [
      'S21 zum Hauptbahnhof, dann U2/U4 (ca. 25-30 Min)',
      'Alternativ mit Auto via B5 in etwa 25 Minuten',
      'Eines der höchstbewerteten Salons: 4.9 Sterne',
      'Spezialisiert auf moderne Herrenschnitte',
      'Professionelle Bartpflege und Gentleman-Service',
    ],
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '21029',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Hamm',
    areaSlug: 'hamm',
    description: 'Balayage in Hamburg-Hamm: Natürliche Highlights mit modernsten Färbetechniken von Spezialistinnen.',
    benefits: [
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Nassrin Karimi ist zertifizierte Balayage-Expertin',
      'Natürlich aussehende, sonnendurchflutete Highlights',
      'Hochwertige Farben für langanhaltende Ergebnisse',
      'Beratung für jeden Haartyp und Wunschfarbe',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Borgfelde',
    areaSlug: 'borgfelde',
    description: 'Balayage in Borgfelde: Nur 5-10 Minuten mit professionellen Balayage-Spezialistinnen.',
    benefits: [
      'Kurze Anfahrt aus Borgfelde – ca. 5-10 Minuten',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Erfahrene Coloristinnen mit Spezialisierung',
      'Natürliche Übergänge ohne harte Ansätze',
      'Beratung für pflegeleichte Farbtrends',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Horn',
    areaSlug: 'horn',
    description: 'Balayage für Horn-Bewohner: Natürliche Highlights mit kurzer Anfahrtszeit.',
    benefits: [
      'Etwa 10 Minuten von Horn entfernt',
      'Spezialisiert auf anspruchsvolle Balayage-Techniken',
      'Erfahrenes Team mit modernstem Know-how',
      'Pflegeleichte Highlights für den Alltag',
      'Langanhaltende Ergebnisse mit hochwertigen Produkten',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Eilbek',
    areaSlug: 'eilbek',
    description: 'Balayage in Eilbek: Spezialisiert auf moderne Färbetechniken für natürliche Highlights.',
    benefits: [
      'Ca. 10 Minuten von Eilbek entfernt',
      'Spezialisiert auf Balayage und moderne Techniken',
      'Mehrsprachiges Team (Deutsch, Englisch, Türkisch, Persisch)',
      'Individuelle Farbberatung nach Haarstruktur',
      'Premium-Produkte für länganhaltende Farbe',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Wandsbek',
    areaSlug: 'wandsbek',
    description: 'Balayage für Wandsbek: Moderne Färbetechniken mit guter U-Bahn-Anbindung.',
    benefits: [
      'Gute Verbindung von Wandsbek via U1 und Busse',
      'Ca. 10-15 Minuten Fahrtzeit',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Erfahrene Coloristinnen mit aktuellem Know-how',
      'Flexible Afterwork-Termine für Berufstätige',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Billstedt',
    areaSlug: 'billstedt',
    description: 'Balayage für Billstedt: Professionelle Highlights mit direkter U2-Verbindung.',
    benefits: [
      'Direkte U2-Verbindung von Billstedt (ca. 15-20 Minuten)',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      '245+ Google-Bewertungen mit 4.9 Sternen',
      'Faire Preise: Balayage ab 179€ inkl. Schnitt',
      'Premium-Produkte für langanhaltende Ergebnisse',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Mitte',
    areaSlug: 'mitte',
    description: 'Balayage für Hamburg-Mitte: Moderne Highlights zentral und leicht erreichbar.',
    benefits: [
      'Ca. 10-15 Minuten von Hamburg-Mitte entfernt',
      'U2/U4 zu Burgstraße, leicht vom Zentrum erreichbar',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Entspannte Atmosphäre weg vom Trubel',
      'Individuelle Farbberatung für jeden Typ',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20099',
  },
  {
    service: 'Balayage',
    serviceSlug: 'balayage',
    area: 'Bergedorf',
    areaSlug: 'bergedorf',
    description: 'Balayage für Bergedorf: Premium-Färbetechniken mit S-Bahn und U-Bahn-Anbindung.',
    benefits: [
      'S21 zum Hauptbahnhof, dann U2/U4 (ca. 25-30 Min)',
      'Alternativ mit Auto via B5 in etwa 25 Minuten',
      'Spezialisiert auf hochwertige Balayage',
      'Eines der besten Salons Hamburgs: 4.9 Sterne',
      'Premium-Service mit individueller Beratung',
    ],
    image: 'https://images.pexels.com/photos/1787295/pexels-photo-1787295.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '21029',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Hamm',
    areaSlug: 'hamm',
    description: 'Haare färben in Hamburg-Hamm: Professionelle Colorationen, Strähnen und Balayage mit Olaplex-Schutz.',
    benefits: [
      'Erfahrene Coloristinnen mit Spezialisierung auf Balayage',
      'Olaplex-Behandlung zum Schutz der Haarstruktur inklusive',
      'Hochwertige Colorationsprodukte für langanhaltende Ergebnisse',
      'Mehrsprachige Beratung (Deutsch, Englisch, Türkisch, Persisch)',
      'Faire Preise: Ansatz ab 43€, Coloration ab 87€',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Borgfelde',
    areaSlug: 'borgfelde',
    description: 'Haare färben in Borgfelde: Nur 5-10 Minuten mit professionellen Colorationen und Balayage.',
    benefits: [
      'Kurze Anfahrt aus Borgfelde – ca. 5-10 Minuten',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Olaplex-Schutz für gesundes, glänzendes Haar',
      'Erfahrene Coloristinnen mit modernstem Know-how',
      'Flexibles Zeitfenster inkl. Afterwork-Termine',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20537',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Horn',
    areaSlug: 'horn',
    description: 'Haare färben für Horn: Professionelle Colorationen mit kurzer Anfahrtszeit.',
    benefits: [
      'Etwa 10 Minuten von Horn entfernt',
      'Spezialisiert auf anspruchsvolle Colorationen',
      'Hochwertige Farben für langanhaltende Ergebnisse',
      'Erfahrenes Team mit modernstem Know-how',
      'Beratung für individuelle Farbwünsche',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Eilbek',
    areaSlug: 'eilbek',
    description: 'Haare färben in Eilbek: Spezialisiert auf Colorationen und Balayage mit Schutzbehandlung.',
    benefits: [
      'Ca. 10 Minuten von Eilbek entfernt',
      'Spezialisiert auf Balayage und moderne Färbetechniken',
      'Olaplex-Behandlung zum Schutz der Haare',
      'Mehrsprachige Farbberatung',
      'Individuelle Konzepte für jeden Haartyp',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Wandsbek',
    areaSlug: 'wandsbek',
    description: 'Haare färben für Wandsbek: Professionelle Colorationen mit guter Anbindung.',
    benefits: [
      'Gute Verbindung von Wandsbek via U1 und Busse',
      'Ca. 10-15 Minuten Fahrtzeit',
      'Spezialisiert auf hochwertige Colorationen',
      'Erfahrene Coloristinnen mit Spezialisierung',
      'Flexible Afterwork-Termine für Pendler',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Billstedt',
    areaSlug: 'billstedt',
    description: 'Haare färben für Billstedt: Professionelle Colorationen mit direkter U2-Verbindung.',
    benefits: [
      'Direkte U2-Verbindung von Billstedt (ca. 15-20 Minuten)',
      'Spezialisiert auf Colorationen und Balayage',
      '245+ Google-Bewertungen mit 4.9 Sternen',
      'Faire Preise: Coloration komplett ab 87€',
      'Hochwertige Produkte für langanhaltende Farbe',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Mitte',
    areaSlug: 'mitte',
    description: 'Haare färben für Hamburg-Mitte: Professionelle Colorationen zentral und leicht erreichbar.',
    benefits: [
      'Ca. 10-15 Minuten von Hamburg-Mitte entfernt',
      'U2/U4 zu Burgstraße, vom Zentrum leicht zu erreichen',
      'Spezialisiert auf Colorationen und Balayage',
      'Olaplex-Schutz für gesundes Haar',
      'Individuelle Farbberatung für Ihren Typ',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '20099',
  },
  {
    service: 'Haare färben',
    serviceSlug: 'haare-faerben',
    area: 'Bergedorf',
    areaSlug: 'bergedorf',
    description: 'Haare färben für Bergedorf: Premium-Colorationen mit S-Bahn und U-Bahn-Anbindung.',
    benefits: [
      'S21 zum Hauptbahnhof, dann U2/U4 (ca. 25-30 Min)',
      'Alternativ mit Auto via B5 in etwa 25 Minuten',
      'Spezialisiert auf hochwertige Colorationen',
      'Eines der beste Salons Hamburgs: 4.9 Sterne',
      'Premium-Service mit individuellem Konzept',
    ],
    image: 'https://images.pexels.com/photos/1444067/pexels-photo-1444067.jpeg?auto=compress&cs=tinysrgb&w=1920',
    plz: '21029',
  },
];
